# Generated by Django 5.0.4 on 2024-04-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spic', models.ImageField(null=True, upload_to='static/sliderimg')),
                ('sdate', models.DateField(null=True)),
            ],
        ),
    ]
