# Generated by Django 5.0.4 on 2024-04-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=200, null=True)),
                ('itempic', models.ImageField(null=True, upload_to='static/itemcategoryimg')),
                ('itemdiscount', models.IntegerField(null=True)),
            ],
        ),
    ]
